# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1033, 815)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dfsButton = QtWidgets.QPushButton(self.centralwidget)
        self.dfsButton.setGeometry(QtCore.QRect(200, 700, 111, 41))
        self.dfsButton.setObjectName("dfsButton")
        self.oradea = QtWidgets.QCheckBox(self.centralwidget)
        self.oradea.setGeometry(QtCore.QRect(130, 50, 91, 19))
        self.oradea.setObjectName("oradea")
        self.zerind = QtWidgets.QCheckBox(self.centralwidget)
        self.zerind.setGeometry(QtCore.QRect(80, 110, 91, 19))
        self.zerind.setObjectName("zerind")
        self.arad = QtWidgets.QCheckBox(self.centralwidget)
        self.arad.setGeometry(QtCore.QRect(40, 180, 91, 19))
        self.arad.setObjectName("arad")
        self.timisoara = QtWidgets.QCheckBox(self.centralwidget)
        self.timisoara.setGeometry(QtCore.QRect(60, 270, 101, 21))
        self.timisoara.setObjectName("timisoara")
        self.lugoj = QtWidgets.QCheckBox(self.centralwidget)
        self.lugoj.setGeometry(QtCore.QRect(150, 350, 91, 19))
        self.lugoj.setObjectName("lugoj")
        self.mehadia = QtWidgets.QCheckBox(self.centralwidget)
        self.mehadia.setGeometry(QtCore.QRect(160, 420, 91, 19))
        self.mehadia.setObjectName("mehadia")
        self.dobreta = QtWidgets.QCheckBox(self.centralwidget)
        self.dobreta.setGeometry(QtCore.QRect(160, 500, 91, 19))
        self.dobreta.setObjectName("dobreta")
        self.sibiu = QtWidgets.QCheckBox(self.centralwidget)
        self.sibiu.setGeometry(QtCore.QRect(260, 220, 91, 19))
        self.sibiu.setObjectName("sibiu")
        self.fagaras = QtWidgets.QCheckBox(self.centralwidget)
        self.fagaras.setGeometry(QtCore.QRect(430, 230, 91, 19))
        self.fagaras.setObjectName("fagaras")
        self.rimnicu = QtWidgets.QCheckBox(self.centralwidget)
        self.rimnicu.setGeometry(QtCore.QRect(320, 330, 131, 21))
        self.rimnicu.setObjectName("rimnicu")
        self.craiova = QtWidgets.QCheckBox(self.centralwidget)
        self.craiova.setGeometry(QtCore.QRect(320, 490, 91, 19))
        self.craiova.setObjectName("craiova")
        self.pitesti = QtWidgets.QCheckBox(self.centralwidget)
        self.pitesti.setGeometry(QtCore.QRect(440, 410, 91, 19))
        self.pitesti.setObjectName("pitesti")
        self.bucharest = QtWidgets.QCheckBox(self.centralwidget)
        self.bucharest.setGeometry(QtCore.QRect(570, 460, 101, 21))
        self.bucharest.setObjectName("bucharest")
        self.giurgiu = QtWidgets.QCheckBox(self.centralwidget)
        self.giurgiu.setGeometry(QtCore.QRect(500, 590, 91, 19))
        self.giurgiu.setObjectName("giurgiu")
        self.urziceni = QtWidgets.QCheckBox(self.centralwidget)
        self.urziceni.setGeometry(QtCore.QRect(720, 410, 91, 19))
        self.urziceni.setObjectName("urziceni")
        self.neamt = QtWidgets.QCheckBox(self.centralwidget)
        self.neamt.setGeometry(QtCore.QRect(650, 120, 91, 19))
        self.neamt.setObjectName("neamt")
        self.lasi = QtWidgets.QCheckBox(self.centralwidget)
        self.lasi.setGeometry(QtCore.QRect(780, 190, 91, 19))
        self.lasi.setObjectName("lasi")
        self.vaslui = QtWidgets.QCheckBox(self.centralwidget)
        self.vaslui.setGeometry(QtCore.QRect(830, 268, 91, 41))
        self.vaslui.setObjectName("vaslui")
        self.hirsova = QtWidgets.QCheckBox(self.centralwidget)
        self.hirsova.setGeometry(QtCore.QRect(870, 420, 91, 19))
        self.hirsova.setObjectName("hirsova")
        self.eforie = QtWidgets.QCheckBox(self.centralwidget)
        self.eforie.setGeometry(QtCore.QRect(900, 550, 91, 19))
        self.eforie.setObjectName("eforie")
        self.bfsButton = QtWidgets.QPushButton(self.centralwidget)
        self.bfsButton.setGeometry(QtCore.QRect(320, 700, 111, 41))
        self.bfsButton.setObjectName("bfsButton")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(440, 700, 111, 41))
        self.clearButton.setObjectName("clearButton")
        self.greedyButton = QtWidgets.QPushButton(self.centralwidget)
        self.greedyButton.setGeometry(QtCore.QRect(560, 700, 111, 41))
        self.greedyButton.setObjectName("greedyButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dfsButton.setText(_translate("MainWindow", "深度优先搜索"))
        self.oradea.setText(_translate("MainWindow", "Oradea"))
        self.zerind.setText(_translate("MainWindow", "ZerInd"))
        self.arad.setText(_translate("MainWindow", "Arad"))
        self.timisoara.setText(_translate("MainWindow", "Timisoara"))
        self.lugoj.setText(_translate("MainWindow", "Lugoj"))
        self.mehadia.setText(_translate("MainWindow", "Mehadia"))
        self.dobreta.setText(_translate("MainWindow", "Dobreta"))
        self.sibiu.setText(_translate("MainWindow", "Sibiu"))
        self.fagaras.setText(_translate("MainWindow", "Fagaras"))
        self.rimnicu.setText(_translate("MainWindow", "Rimnicu Vicea"))
        self.craiova.setText(_translate("MainWindow", "Craiova"))
        self.pitesti.setText(_translate("MainWindow", "Pitesti"))
        self.bucharest.setText(_translate("MainWindow", "Bucharest"))
        self.giurgiu.setText(_translate("MainWindow", "Giurgiu"))
        self.urziceni.setText(_translate("MainWindow", "Urziceni"))
        self.neamt.setText(_translate("MainWindow", "Neamt"))
        self.lasi.setText(_translate("MainWindow", "Lasi"))
        self.vaslui.setText(_translate("MainWindow", "Vaslui"))
        self.hirsova.setText(_translate("MainWindow", "Hirsova"))
        self.eforie.setText(_translate("MainWindow", "Eforie"))
        self.bfsButton.setText(_translate("MainWindow", "广度优先搜索"))
        self.clearButton.setText(_translate("MainWindow", "清除"))
        self.greedyButton.setText(_translate("MainWindow", "贪婪算法"))
